# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd9ba02ce27511f243ef034cde5312771bb46ed27eec04f59c89d4499fe4e3f1603131c38a77ae2d0a096df387036e1327c411e773ccdf78d987956d6439b84e

test:
  secret_key_base: d6fde1399e0fa85fef789539ae6ffe719f198a08df02356f3507d7868c4deedc24adc7a5087ce26389bfc4c07bec3e31e80bc2d68ad9799e52901b8b82951440

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
